### ISSUE TITLE
No video on HLS feeds

### ISSUE THREAD

**Issue by Rushmead** [alfg/docker-nginx-rtmp#64] opened 2020-04-25 14:52 UTC
Hey

Im running the most recent version of the image with the default config and I'm getting no video feeds, but I am getting audio.

Here is what stats says

![image](https://user-images.githubusercontent.com/1780637/80283026-b092f600-870c-11ea-92dc-ad9521753e8b.png)

As you can see there is no resolutions for the transcoded feeds. I'm running it on a fairly beefy machine so I don't imagine its anything to do with resources.

Any help would be appreciated.

**Comment by alfg** [comment] 2020-04-25 18:13
Hi @Rushmead,

That's strange that you're getting audio, but no video. Which RTMP client are you using? I tried the latest image with default configs using OBS 25.0.1 and I am getting both audio and video.

![rtmp](https://user-images.githubusercontent.com/702541/80287319-c2ad6e00-86e5-11ea-879a-9a6bc801540d.PNG)

**Comment by Rushmead** [comment] 2020-04-25 18:27
I'm using OBS 25.0.4 to stream and I'm using the VideoJS player to display it. I've tried using VLC to get the raw RTMP feed and I get the video there.

I tried running the ffmpeg manually myself inside the container but that seems to fail with a message saying "Too many buffered packets in 0:1".

**Comment by cerrbeer** [comment] 2020-04-29 10:26
Hello. Im using OBS 25.0.8 and i have same issues in two bilds 1.0 and latest . Only audio.  But she repeats once from 20-30 streams. I did not find 100% of the reasons for how to reproduce it.  Maybe if at start a very low speed    

![index2](https://user-images.githubusercontent.com/6719402/80585997-eaba0b80-8a1c-11ea-8c57-05d81c72d09f.png)



![index](https://user-images.githubusercontent.com/6719402/80584206-02dc5b80-8a1a-11ea-8598-b0a01c18ac8e.png)


Logs:

```
2020/04/29 09:54:44 [notice] 10#10: signal 17 (SIGCHLD) received from 358
2020/04/29 09:54:44 [notice] 10#10: unknown process 358 exited with code 1
2020/04/29 09:54:44 [info] 10#10: *20 exec: terminating child 358, client: 178.74.237.60, server: 0.0.0.0:1935
2020/04/29 09:54:46 [info] 10#10: *27 client closed connection while waiting for request, client: 178.74.237.60, server: 0.0.0.0:80
178.74.237.60 - - [29/Apr/2020:09:54:46 +0000] "GET /stat HTTP/1.1" 200 1501 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
178.74.237.60 - - [29/Apr/2020:09:54:47 +0000] "GET /stat HTTP/1.1" 200 1499 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
178.74.237.60 - - [29/Apr/2020:09:54:48 +0000] "GET /stat HTTP/1.1" 200 1501 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
2020/04/29 09:54:49 [info] 10#10: *20 exec: starting managed child 'ffmpeg', client: 178.74.237.60, server: 0.0.0.0:1935
2020/04/29 09:54:50 [info] 10#10: *35 client connected '127.0.0.1'
2020/04/29 09:54:50 [info] 10#10: *35 connect: app='stream' args='' flashver='LNX 9,0,124,2' swf_url='' tc_url='rtmp://localhost:1935/stream' page_url='' acodecs=4071 vcodecs=252 object_encoding=0, client: 127.0.0.1, server: 0.0.0.0:1935
2020/04/29 09:54:50 [info] 10#10: *35 createStream, client: 127.0.0.1, server: 0.0.0.0:1935
2020/04/29 09:54:50 [info] 10#10: *35 play: name='hello' args='' start=-2000 duration=0 reset=0 silent=0, client: 127.0.0.1, server: 0.0.0.0:1935
2020/04/29 09:54:55 [info] 10#10: *36 client connected '127.0.0.1'
2020/04/29 09:54:55 [info] 10#10: *36 connect: app='hls' args='' flashver='FMLE/3.0 (compatible; Lavf58.29' swf_url='' tc_url='rtmp://localhost:1935/hls' page_url='' acodecs=0 vcodecs=0 object_encoding=0, client: 127.0.0.1, server: 0.0.0.0:1935
2020/04/29 09:54:55 [info] 10#10: *36 createStream, client: 127.0.0.1, server: 0.0.0.0:1935
2020/04/29 09:54:55 [info] 10#10: *36 publish: name='hello_720p2628kbs' args='' type=live silent=0, client: 127.0.0.1, server: 0.0.0.0:1935
2020/04/29 09:54:55 [info] 10#10: *37 client connected '127.0.0.1'
2020/04/29 09:54:55 [info] 10#10: *37 connect: app='hls' args='' flashver='FMLE/3.0 (compatible; Lavf58.29' swf_url='' tc_url='rtmp://localhost:1935/hls' page_url='' acodecs=0 vcodecs=0 object_encoding=0, client: 127.0.0.1, server: 0.0.0.0:1935
2020/04/29 09:54:55 [info] 10#10: *37 createStream, client: 127.0.0.1, server: 0.0.0.0:1935
2020/04/29 09:54:55 [info] 10#10: *37 publish: name='hello_480p1128kbs' args='' type=live silent=0, client: 127.0.0.1, server: 0.0.0.0:1935
2020/04/29 09:54:56 [info] 10#10: *38 client connected '127.0.0.1'
2020/04/29 09:54:56 [info] 10#10: *38 connect: app='hls' args='' flashver='FMLE/3.0 (compatible; Lavf58.29' swf_url='' tc_url='rtmp://localhost:1935/hls' page_url='' acodecs=0 vcodecs=0 object_encoding=0, client: 127.0.0.1, server: 0.0.0.0:1935
2020/04/29 09:54:56 [info] 10#10: *38 createStream, client: 127.0.0.1, server: 0.0.0.0:1935
2020/04/29 09:54:56 [info] 10#10: *38 publish: name='hello_360p878kbs' args='' type=live silent=0, client: 127.0.0.1, server: 0.0.0.0:1935
2020/04/29 09:54:56 [info] 10#10: *39 client connected '127.0.0.1'
2020/04/29 09:54:56 [info] 10#10: *39 connect: app='hls' args='' flashver='FMLE/3.0 (compatible; Lavf58.29' swf_url='' tc_url='rtmp://localhost:1935/hls' page_url='' acodecs=0 vcodecs=0 object_encoding=0, client: 127.0.0.1, server: 0.0.0.0:1935
2020/04/29 09:54:56 [info] 10#10: *39 createStream, client: 127.0.0.1, server: 0.0.0.0:1935
2020/04/29 09:54:56 [info] 10#10: *39 publish: name='hello_240p528kbs' args='' type=live silent=0, client: 127.0.0.1, server: 0.0.0.0:1935
2020/04/29 09:54:56 [info] 10#10: *40 client connected '127.0.0.1'
2020/04/29 09:54:56 [info] 10#10: *40 connect: app='hls' args='' flashver='FMLE/3.0 (compatible; Lavf58.29' swf_url='' tc_url='rtmp://localhost:1935/hls' page_url='' acodecs=0 vcodecs=0 object_encoding=0, client: 127.0.0.1, server: 0.0.0.0:1935
2020/04/29 09:54:56 [info] 10#10: *40 createStream, client: 127.0.0.1, server: 0.0.0.0:1935
2020/04/29 09:54:56 [info] 10#10: *40 publish: name='hello_240p264kbs' args='' type=live silent=0, client: 127.0.0.1, server: 0.0.0.0:1935
2020/04/29 09:54:58 [info] 10#10: *34 client closed connection while waiting for request, client: 178.74.237.60, server: 0.0.0.0:80
178.74.237.60 - - [29/Apr/2020:09:54:58 +0000] "GET /stat HTTP/1.1" 200 5061 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
178.74.237.60 - - [29/Apr/2020:09:54:59 +0000] "GET /stat HTTP/1.1" 200 5061 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
178.74.237.60 - - [29/Apr/2020:09:55:00 +0000] "GET /stat HTTP/1.1" 200 5061 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
178.74.237.60 - - [29/Apr/2020:09:55:00 +0000] "GET /stat HTTP/1.1" 200 5074 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
2020/04/29 09:55:58 [info] 10#10: *41 client timed out (110: Operation timed out) while waiting for request, client: 178.74.237.60, server: 0.0.0.0:80
```

**Comment by alfg** [comment] 2020-04-29 19:15
Thanks for the info @cerrbeer. I'll keep digging. I am not able to reproduce the issue so far.

**Comment by RussianCatYakov** [comment] 2020-05-08 22:22
I might help you because i encountered the same problem while using OBS Studio. The problem is in key frame interval in default settings, it is set to 0 ( which is automatic but idk what does it mean). I manually set it to once per 2 seconds and it works perfectly now.

**Comment by alfg** [comment] 2020-05-09 02:26
@RussianCatYakov what is the key frame interval setting you are using? I don't see it in https://github.com/arut/nginx-rtmp-module/wiki/Directives

**Comment by RussianCatYakov** [comment] 2020-05-12 18:59
@alfg im talking about OBS. I set key frame interval in obs to 2 sec and it works just fine.
i did not face this problem when i used ffmpeg to simply copy rtmp stream from localhost to remote machine that runs your container.
so i assume its obs problem, you can check out my settings on the screenshot
![image](https://user-images.githubusercontent.com/48888429/81734120-b3774000-949b-11ea-894b-e318e6b90484.png)

**Comment by alfg** [comment] 2020-05-13 05:43
Thanks for the info @RussianCatYakov. I will keep checking into this.

**Comment by alfg** [comment] 2021-01-30 08:40
Closing for now. Feel free to re-open or comment if anyone else is still having this issue.

**Closed by alfg** 2021-01-30 08:40 UTC
