### ISSUE TITLE
HTTPS Live Stream does not work behind a reverse proxy

### ISSUE THREAD

**Issue by starwarskidfan** [alfg/docker-nginx-rtmp#40] opened 2020-02-06 03:10 UTC
For some reason, the HTTP stream does not work behind a reverse proxy.

At least that is what I think the problem is.

Here is a paste for the stat

![image](https://user-images.githubusercontent.com/10633208/73902641-16818700-485c-11ea-81c9-b6b2ebd7f93a.png)

**Comment by alfg** [comment] 2020-02-06 03:27
Hi @starwarskidfan, 

Do you have an example nginx config you can paste?

**Comment by starwarskidfan** [comment] 2020-02-06 03:35
It is just the default nginx config. Haven't changed it at all or even bound the volume to look at it.

**Comment by alfg** [comment] 2020-02-06 05:46
The default nginx config of this project?

**Comment by alfg** [comment] 2020-02-06 06:05
Running locally, using the latest build from master seems to be OK:
![Capture](https://user-images.githubusercontent.com/702541/73910188-72034300-4863-11ea-9585-02ed2ebaa94d.PNG)

Are you running this in a hosted environment and have the right firewall rules to allow 1935 for rtmp?

**Comment by starwarskidfan** [comment] 2020-02-06 06:09
Ya, I basically I can see the rtmp stream, but the http stream I am only getting audio. It is behind a traefik reverse proxy. I have 1935 open while the http part is behind the proxy.

**Comment by starwarskidfan** [comment] 2020-02-06 06:11
Yeah, I don't have a video codec for my http. Using alfg/nginx-rtmp latest.

**Comment by alfg** [comment] 2020-02-09 04:39
Can you share an example of the traefik config? I haven't been able to reproduce this issue yet.

**Comment by alfg** [comment] 2020-03-11 03:23
Closing. Feel free to reopen if you have any additional information.

**Closed** 2020-03-11 03:23 UTC
