### ISSUE TITLE
hls streaming not working

### ISSUE THREAD

**Issue by corneliusweiss** [alfg/docker-nginx-rtmp#54] opened 2020-03-17 20:16 UTC
Hi, 

I'm new to the topic of streaming, so I hope this issue isn't stupid.

I can start streaming from obs.
Consuming the stream is working using rtmp at `rtmp://serverIP/stream/test` but _not_ with hls at `http://serverIP:8080/live/test.m3u8`

In the logs I get:
```
2020/03/17 20:06:10 [error] 7#7: *8 open() "/opt/data/hls/test.m3u8" failed (2: No such file or directory), client: 95.91.228.154, server: , request: "GET /live/test.m3u8 HTTP/1.1", host: "serverIP:8080"
clientIP - - [17/Mar/2020:20:06:10 +0000] "GET /live/test.m3u8 HTTP/1.1" 404 555 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/82.0.4061.0 Safari/537.36"
```

thanks in advance
Cornelius

**Comment by corneliusweiss** [comment] 2020-03-17 22:05
ok, ic. envsubst is the problem
```
-c:a libfdk_aac -b:a 128k -c:v libx264 -b:v 2500k -f flv -g 30 -r 30 -s 1280x720 -preset superfast -profile:v baseline rtmp://localhost:1935/hls/$name_720p2628kbs
```
envsubst substitutes `$name_720p2628kbs` to empty string

see pull request #55

**Comment by andrewc2** [comment] 2020-03-17 23:03
Ughhh I hate when I wake up to my server being down because something got changed again here that either moves or updates files that didn't previously exist.

**Comment by absentio** [comment] 2020-03-17 23:46
Update command like this:`envsubst "$(env | sed -e 's/=.*//' -e 's/^/\$/g')" < nginx.conf.template > nginx.conf'

**Comment by andrewc2** [comment] 2020-03-18 00:02
How can I not use any of this `envsubst` thing. It's literally messed up so much.

**Comment by alfg** [comment] 2020-03-18 00:07
@andrewc2 You should maintain a fork and only pull in changes from upstream as needed. Pulling from master or latest image is not an ideal setup if you don't want the latest changes every time something is merged.

**Comment by andrewc2** [comment] 2020-03-18 00:36
> @alfg Good plan.

**Comment by pethil** [comment] 2020-03-18 12:28
It still doesn't work for me. I get this error

 ```
2020/03/18 14:35:10 [error] 8#8: *4 open() "/opt/data/hls/test.m3u8" failed (2: No such file or directory), client: 192.168.178.75, server: , request: "GET /live/test.m3u8 HTTP/1.0", host: "nas.home:8080"
192.168.178.75 - - [18/Mar/2020:14:35:10 +0000] "GET /live/test.m3u8 HTTP/1.0" 404 153 "-" "VLC/3.0.8 LibVLC/3.0.8"
```

while the command 

ffplay -fflags nobuffer rtmp://nas.home:1935/stream/test

works completely fine and shows me the stream.

I've pulled the latest image from last night. I am not sure how I would use the suggested envsubst command.

**Comment by alfg** [comment] 2020-03-18 17:37
@pethil hoping to have this fixed as part of https://github.com/alfg/docker-nginx-rtmp/pull/55. 

If it's causing too much complication, I will change it back.

**Comment by alfg** [comment] 2020-03-19 02:21
Hey guys, sorry for the delay. I've added the suggested fix from @absentio (thank you) to the latest build and confirmed it works. Feel free to pull the latest image.

https://github.com/alfg/docker-nginx-rtmp/commit/3a6b69a6e80e8f90e30f838aef5193cda85eb47d

**Closed** 2020-03-19 02:45 UTC

**Comment by creimers** [comment] 2020-04-23 09:18
I still get 404s in the browser or VLC using `http://localhost:8080/live/stream.m3u8` on `alfg/nginx-rtmp:latest` while ffplay and VLC on `rtmp://localhost:1935/stream` work...

Am I missing something?

**Comment by alfg** [comment] 2020-04-25 04:48
@creimers are you sure you have the latest image pulled? Which docker image ID are you using?

**Comment by creimers** [comment] 2020-04-28 11:35
@alfg I'm quite sure, yes. Look at this screenshot:

<img width="607" alt="Bildschirmfoto 2020-04-28 um 13 32 59" src="https://user-images.githubusercontent.com/6090492/80482751-1376ce00-8955-11ea-89ab-7bd970225eee.png">
