### ISSUE TITLE
HLS stream cuts after a few seconds.

### ISSUE THREAD

**Issue by michaeltoohig** [alfg/docker-nginx-rtmp#57] opened 2020-03-19 21:34 UTC
When I try to watch the HLS stream it closes the connection after ~5/6 seconds. Only rarely has the stream continued beyond the 5 seconds and the resolution improved, but eventually fails most times.

Below is the log I see in terminal at time of connecting to the stream until the connection drops.

```
nginx-rtmp_1  | 10.0.2.3 - - [19/Mar/2020:21:22:15 +0000] "GET /live/test.m3u8 HTTP/1.1" 206 500 "-" "VLC/3.0.7.1 LibVLC/3.0.7.1"
nginx-rtmp_1  | 10.0.2.3 - - [19/Mar/2020:21:22:15 +0000] "GET /live/test_240p264kbs/index.m3u8 HTTP/1.1" 206 137 "-" "VLC/3.0.7.1 LibVLC/3.0.7.1"
nginx-rtmp_1  | 2020/03/19 21:22:15 [info] 6#6: *18 client 10.0.2.3 closed keepalive connection
nginx-rtmp_1  | 10.0.2.3 - - [19/Mar/2020:21:22:15 +0000] "GET /live/test_240p264kbs/index.m3u8 HTTP/1.1" 206 137 "-" "VLC/3.0.7.1 LibVLC/3.0.7.1"
nginx-rtmp_1  | 2020/03/19 21:22:15 [info] 6#6: *19 client 10.0.2.3 closed keepalive connection
nginx-rtmp_1  | 10.0.2.3 - - [19/Mar/2020:21:22:15 +0000] "GET /live/test_240p264kbs/1584652922273.ts HTTP/1.1" 200 179352 "-" "VLC/3.0.7.1 LibVLC/3.0.7.1"
nginx-rtmp_1  | 10.0.2.3 - - [19/Mar/2020:21:22:15 +0000] "GET /live/test_720p2628kbs/index.m3u8 HTTP/1.1" 206 137 "-" "VLC/3.0.7.1 LibVLC/3.0.7.1"
nginx-rtmp_1  | 2020/03/19 21:22:15 [info] 6#6: *21 client 10.0.2.3 closed keepalive connection
nginx-rtmp_1  | 2020/03/19 21:22:21 [info] 6#6: *20 client 10.0.2.3 closed keepalive connection
nginx-rtmp_1  | 2020/03/19 21:22:21 [info] 6#6: *17 client 10.0.2.3 closed keepalive connection
```

In case it matters, the RTMP stream does work at full resolution.

**Comment by alfg** [comment] 2020-03-21 01:15
What kind of system resources are you running? Is it possible the hls variants are not keeping up?

You can also try removing some of the variants and see if it helps.

**Comment by michaeltoohig** [comment] 2020-03-24 03:07
I'm currently running only two of the variants to be sure but still it cuts off but I noticed now its only for VLC. The same URL works fine when loaded and playing via video.js.

Its running on a VM with 4GB of RAM and and 8 cores which should be more than enough, right?

**Comment by alfg** [comment] 2020-03-24 03:38
Ah, I see the same issue. However, I tried upgrading to VLC 3.0.8 and it seems to keep playing, but seems a bit laggy.

Which VLC are you on?

**Comment by alfg** [comment] 2020-03-24 03:40
Also found this in the release notes. So maybe a fixed bug?

https://www.videolan.org/developers/vlc-branch/NEWS

```
Changes between 3.0.8 and 3.0.9:
----------------------------------
Demux:
 * Fix adaptive regression on TS format change (mostly HLS)
```

**Comment by michaeltoohig** [comment] 2020-03-24 03:56
I am on version 3.0.8.

**Comment by RussianCatYakov** [comment] 2020-05-08 22:26
I'm sure i know what the problem is but idk why it happens. As you can see VLC tries to get master playlist in range queries which is pretty much stupid for a simple text file. For now i set max_ranges 0 in nginx conf to disable range queries at all.

**Comment by michaeltoohig** [comment] 2020-06-15 23:37
@RussianCatYakov I set `max_ranges` to 0 in the `/hls` location and afterwards VLC behaves worse than before. It doesn't drop the connection any longer but it always loading and plays maybe 1 second before failing again loading the next segment.

Is that the place I should put `max_ranges`?

**Comment by RussianCatYakov** [comment] 2020-06-19 10:11
@michaeltoohig I set it in hls section too, yes. You see, it disables range queries for .ts segments too, which can be a problem for people with kind of slow internet. It tries to download the whole segment and it might take some time. 
There are two ways to fix this:
1. Make .ts segment last less seconds. I'd recommend 5 sec * 3 segments in one playlist. It is kind of a standard value for HLS. 
2. Disable range requests only for *.m3u8 links via location or an if statement. I haven't tried it but i think it should work.

**Comment by alfg** [comment] 2021-01-30 08:39
Closing for now. Feel free to comment if anyone else is still having this issue.

**Closed by alfg** 2021-01-30 08:39 UTC
